config/routes.rb
Propertymanagement::Application.routes.draw do
  resources :user_sessions

  resources :repair_requests

  resources :leases

  resources :units

  resources :properties

  resources :users
  
  root :to => 'users#index'
  
  match 'login', :to => 'user_sessions#new'
  
  match 'logout', :to => 'user_sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Propertymanagement</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Begin Wrapper -->
<div id="wrapper">
	
	<!-- Begin Header -->
	<div id="header">
		
		This is the header
		
	</div>
	<!-- End Header -->
	
	<!-- Begin Navigation -->
	<div id="navigation">
		
		<div id="login">
			
			<% if current_user %>
				
				<%= link_to "Edit Profile", edit_user_path(:current) %>
				<%= link_to "Logout", logout_path %>
				
			<% else %>
			
				<%= link_to "Register", new_user_path %>
				<%= link_to "Login", login_path %>
			
			<% end %>
			
		</div>
		
	</div>
	<!-- End Navigation -->
	
	<!-- Begin Lef Column -->
	<div id="leftcolumn">
		
		<% if flash[:error] -%>
			<div id='error'><%=h flash[:error] %></div>
		<% end -%>
		<% if flash[:notice] -%>
			<div id='notice'><%=h flash[:notice] %></div>
		<% end -%><br /><br />
			
		<%= yield %>
		
	</div>
	<!-- End Left Column -->
	
	<!-- Begin Footer -->
	<div id="footer">
		
		This is the footer
		
	</div>
	<!-- End Footer -->
	
</div>
<!-- End Wrapper -->

</body>
</html>